# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/337c5869-4ec8-4158-bdf2-d8d91fc75a7d";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DA51-D155";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
  
  fileSystems."/nvme2" =
    { device = "/dev/disk/by-uuid/f094da54-c59f-40c5-9862-a8d3f560b6c5";
      fsType = "ext4";
      options = [ 
        "defaults" 
        "noatime"      # Beste Option für Gaming: Verhindert Schreibzugriffe beim Lesen
        "nodiratime"   # Verhindert Verzeichnis-Zeitstempel-Updates
        "lazytime"     # Schont die SSD zusätzlich
        "commit=60"    # Schreibt Daten gesammelt alle 60 Sek (erhöht Performance)
      ];
    };


   swapDevices = [ 
    { 
      device = "/dev/disk/by-uuid/fd20d41a-b995-441e-9c29-3b5dee9abc58"; 
      priority = 0; # Niedrige Priorität: Nur nutzen, wenn zRAM voll ist
    }
   ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
