# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d9f29026-6717-4557-9cd2-fde68e0a608f";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4F8D-8568";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
   
  fileSystems."/gaming" = {
    device = "/dev/disk/by-uuid/f094da54-c59f-40c5-9862-a8d3f560b6c5";
    fsType = "ext4";
    options = [ 
      "defaults"
      "noatime"   # Verhindert ständiges Schreiben der Zugriffszeit
      "nodiratime"
      "discard"   # Aktiviert Continuous TRIM für NVMe
      "commit=60" # Schreibt Daten gesammelt alle 60 Sek (schont die SSD)
      "nofail"
    ];
  };  
  swapDevices =
    [ { device = "/dev/disk/by-uuid/e368c4bd-7749-4c65-84be-bc58754e0a27"; 
        priority = 0; # Niedrige Priorität: Nur nutzen, wenn zRAM voll ist
      }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
