[colors]
background = "#eeeeeeFF"
text_primary = "#1b1b1bFF"
text_muted = "#474747FF"
accent_primary = "#8d4f00FF"
accent_secondary = "#735943FF"
warning = "#5a6238FF"
error = "#ba1a1aFF"
insert_hint = "#5a623880"
backdrop = "#e2e2e2FF"

[colors.border]
focused = "#8d4f00FF"
unfocused = "#e2e2e2FF"
scratchpad_focused = "#5a6238FF"
scratchpad_unfocused = "#dee8b2FF"
outer = "#f9f9f9FF"

[colors.overview]
background_tint = "#f9f9f988"
badge = "#8d4f00FF"
workspace_background = "#f9f9f9FF"
