[colors]
background = "#eeeeeeF0"
text_primary = "#1b1b1bFF"
text_muted = "#474747FF"
accent_primary = "#944a01FF"
accent_secondary = "#755845FF"
warning = "#5f6135FF"
error = "#ba1a1aFF"

[appearance]
border_focused = "#944a01FF"
border_unfocused = "#e2e2e2FF"
scratchpad_border_focused = "#5f6135FF"
scratchpad_border_unfocused = "#e5e6aeFF"
outer_border_color = "#f9f9f9FF"
insert_hint_color = "#5f613580"
backdrop_color = "#e2e2e2FF"

[overview]
background_tint = "#f9f9f988"
