[colors]
background = "#eeeeeeFF"
text_primary = "#1b1b1bFF"
text_muted = "#474747FF"
accent_primary = "#855300FF"
accent_secondary = "#715a41FF"
warning = "#54643dFF"
error = "#ba1a1aFF"
insert_hint = "#54643d80"
backdrop = "#e2e2e2FF"

[colors.border]
focused = "#855300FF"
unfocused = "#e2e2e2FF"
scratchpad_focused = "#54643dFF"
scratchpad_unfocused = "#d7e9b9FF"
outer = "#f9f9f9FF"

[colors.overview]
background_tint = "#f9f9f988"
badge = "#855300FF"
workspace_background = "#f9f9f9FF"
