[colors]
background = "#eeeeeeFF"
text_primary = "#1b1b1bFF"
text_muted = "#474747FF"
accent_primary = "#4659a9FF"
accent_secondary = "#5a5d72FF"
warning = "#76546eFF"
error = "#ba1a1aFF"
insert_hint = "#76546e80"
backdrop = "#e2e2e2FF"

[colors.border]
focused = "#4659a9FF"
unfocused = "#e2e2e2FF"
scratchpad_focused = "#76546eFF"
scratchpad_unfocused = "#ffd7f3FF"
outer = "#f9f9f9FF"

[colors.overview]
background_tint = "#f9f9f988"
badge = "#4659a9FF"
workspace_background = "#f9f9f9FF"
