[bar.default]
background_opacity = 0.88
capsule = true
contact_shadow = true

[calendar]
enabled = false

[dock]
auto_hide = true
enabled = true
icon_size = 36
margin_edge = 0
reserve_space = false

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

[idle.behavior.lock]
action = "lock"
enabled = true
timeout = 600

[idle.behavior.lock-and-suspend]
action = "lock_and_suspend"
enabled = true
timeout = 900

[idle.behavior.screen-off]
action = "screen_off"
enabled = true
timeout = 660

[location]
address = "Barsinghausen"
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

[lockscreen_widgets.grid]
cell_size = 16
major_interval = 4
visible = true

[lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
box_height = 0.0
box_width = 0.0
cx = 960.0
cy = 957.0
output = "eDP-1"
rotation = 0.0
type = "login_box"

[lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
background_color = "surface_variant"
background_opacity = 0.88
background_radius = 12.0
input_opacity = 1.0
input_radius = 6.0
show_login_button = true

[shell]
password_style = "random"
polkit_agent = true
settings_show_advanced = true
telemetry_enabled = true

[shell.panel]
transparency_mode = "glass"

[theme]
mode = "light"
source = "wallpaper"

[wallpaper]
directory = "/home/mortiferus/Bilder/Wallpaper-NSFW"
transition_on_startup = true

[wallpaper.automation]
enabled = true

[widget.battery]
show_label = false

[widget.brightness]
show_label = false

[widget.network]
show_label = false

[widget.volume]
show_label = false
