color0 #f9f9f9
color1 #ba1a1a
color2 #934b00
color3 #755945
color4 #5e6135
color5 #ffb782
color6 #e4bfa7
color7 #1b1b1b
color8 #777777
color9 #ba1a1a
color10 #934b00
color11 #755945
color12 #5e6135
color13 #ffb782
color14 #e4bfa7
color15 #1b1b1b

cursor                #1b1b1b
cursor_text_color     #f9f9f9
background            #f9f9f9
foreground            #1b1b1b
selection_foreground  #474747
selection_background  #e2e2e2
active_border_color   #934b00
inactive_border_color #e2e2e2
url_color             #934b00
