$primary = rgb(3258bc)
$surface = rgb(faf8ff)
$secondary = rgb(515d85)
$error = rgb(ba1a1a)
$tertiary = rgb(87409d)
$surface_lowest = rgb(ffffff)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
